import style from "@/styles/common/sidebar.module.sass";

const Sidebar = () => {
  return (
    <div className={style.sidebar}>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
      <div>Sidebar</div>
    </div>
  );
};

export default Sidebar;
